version: '3.9'
services:
  webapi:
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://+:5000;https://+:5001"
      ConnectionStrings__MongoDb: "mongodb://admin:admin123@mongodb:27017/TodoList?authSource=admin&serverSelectionTimeoutMS=30000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

volumes:
  mongo_data:

