@WebAPI_HostAddress = https://localhost:7297

### Listar todos os itens
GET {{WebAPI_HostAddress}}/api/todos
Accept: application/json

### Adicionar um novo item
POST {{WebAPI_HostAddress}}/api/todos
Content-Type: application/json
Accept: application/json

{
  "title": "task4"
}

### Marcar um item como concluído
PUT {{WebAPI_HostAddress}}/api/todos/{{id}}/complete
Content-Type: application/json
Accept: application/json

### Excluir um item
DELETE {{WebAPI_HostAddress}}/api/todos/{{id}}
Accept: application/json